# Generated by Django 4.0.3 on 2023-12-23 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia_game_app', '0002_alter_player_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='media',
            field=models.BooleanField(default=False),
        ),
    ]
